spring:
  # 临时解决doc
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: zmz121.cn:8848
  config:
    import:
      - optional:nacos:user-service.yaml  # 监听 DEFAULT_GROUP:test.yml

#spring:
#  application:
#    name: user-service
#  main:
#    allow-bean-definition-overriding: true
#
#
#nacos:
#  config:
#    server-addr: zmz121.cn:8848
#    bootstrap:
#      enable: true
#    type: yaml
#    data-id: user-service.yaml